Kwp simulation
iwanders/OBD9141 pull request #53
Opened 2023-12-19 23:58 UTC by ankayca

KWP message frame added to simulation side. MC3360 and arduino uno used for tests. This my first pull request so I anything wrong my bad.

2023-12-20 22:52 UTC, iwanders requested changes
Hey @ankayca, thanks for taking the time to file this PR. I'm always pleasantly surprised when the simulator is useful to anyone but me, as I only really wrote it as a development tool for my own projects.

I made a few minor remarks on the code, if you could incorporate those we should be able to merge it.

2023-12-20 22:52 UTC, iwanders commented on src/OBD9141sim.h
> +        bool use_kwp_;
Please assign this to be false in the constructor, so next to 
https://github.com/iwanders/OBD9141/blob/838bd4a46490dfa8f70e25217fd4fff337e14fa3/src/OBD9141sim.cpp#L15

2023-12-20 22:52 UTC, iwanders commented on src/OBD9141sim.cpp
> +    if(use_kwp_){
```suggestion
    if (use_kwp_){
```

2023-12-20 22:52 UTC, iwanders commented on src/OBD9141sim.cpp
> +        message[0] = 0x82 + (answer->len );
```suggestion
        message[0] = 0x82 + answer->len;
```

2023-12-20 22:52 UTC, iwanders commented on src/OBD9141sim.cpp
> +    use_kwp_ = true;
```suggestion
    this->use_kwp_ = true;
```

I know it's not necessary, but the other code follows this pattern, so lets keep it similar.

2023-12-21 21:19 UTC, ankayca reviewed
I gonna continue to work with this simulator. Its very useful and there are not too much information about K line on the internet and thanks for your reviews.

2023-12-21 22:14 UTC, iwanders commented on src/OBD9141sim.h
> +        bool use_kwp_;
Please incorporate this feedback, other than that it looks good now, thanks for incorporating the others.

2023-12-21 22:15 UTC, iwanders commented
One comment about adding the assignment of `use_kwp_` to false in the constructor wasn't addressed, please add that, other than that it looks good.

2023-12-22 00:06 UTC, ankayca reviewed
my bad. assigned

2023-12-22 00:07 UTC, iwanders commented
Looks good now, I'm going to merge this.

Thanks for your contribution @ankayca !

2023-12-22 00:07 UTC, merged